return {
  require 'kickstart.plugins.utilities.telescope',
  require 'kickstart.plugins.utilities.harpoon',
  require 'kickstart.plugins.utilities.fzf',
  require 'kickstart.plugins.utilities.lualine',
  require 'kickstart.plugins.utilities.eyeliner',
  require 'kickstart.plugins.utilities.autosession',
  require 'kickstart.plugins.utilities.lazygit',
  require 'kickstart.plugins.utilities.dropbar',
  require 'kickstart.plugins.utilities.neo-tree',
  require 'kickstart.plugins.utilities.mini',
  require 'kickstart.plugins.utilities.mini-icons',
  require 'kickstart.plugins.utilities.oil',
  require 'kickstart.plugins.utilities.noneckpain',
  require 'kickstart.plugins.utilities.markdown_render',
  require 'kickstart.plugins.utilities.mkdnflow',
  -- require 'kickstart.plugins.utilities.neorg',
  -- require 'kickstart.plugins.utilities.surround',
  -- require 'kickstart.plugins.utilities.barbecue',
}
