return {
  require 'kickstart.plugins.core.lsp',
  require 'kickstart.plugins.core.vimsleuth',
  require 'kickstart.plugins.core.lint',
  require 'kickstart.plugins.core.gitsigns',
  require 'kickstart.plugins.core.debug',
  require 'kickstart.plugins.core.autopairs',
  require 'kickstart.plugins.core.autocomplete',
  require 'kickstart.plugins.core.which',
  require 'kickstart.plugins.core.highlights',
  require 'kickstart.plugins.core.autoformat',
  require 'kickstart.plugins.core.treesitter',
  require 'kickstart.plugins.core.trouble',
  require 'kickstart.plugins.core.bufdelete',
  -- require 'kickstart.plugins.core.mini-indentscope',
  -- require 'kickstart.plugins.core.indent_line',
}
